# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Extension tests"

on:
  workflow_call:
    inputs:
      ref:
        description: 'phpstan/phpstan ref to checkout'
        required: true
        type: string
      phar-checksum:
        description: 'PHAR checksum from reproducible build (please rebase)'
        required: true
        type: string

jobs:
  check-phar-checksum:
    name: "Check PHAR checksum"
    runs-on: "ubuntu-latest"
    outputs:
      checksum-result: ${{ steps.checksum-difference.outputs.result }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: "phpstan/phpstan"
          ref: ${{ inputs.ref }}
      - name: "Check PHAR checksum"
        id: checksum-difference
        run: |
          checksum=${{ inputs.phar-checksum }}
          if [[ $(head -n 1 .phar-checksum) != "$checksum" ]]; then
            echo "result=different" >> $GITHUB_OUTPUT
          else
            echo "result=same" >> $GITHUB_OUTPUT
          fi

  tests-extensions:
    name: "${{ matrix.extension-name }} (${{ matrix.php-version }}) ${{ matrix.script }}"

    runs-on: "ubuntu-latest"

    needs: check-phar-checksum
    if: "needs.check-phar-checksum.outputs.checksum-result == 'different'"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        extension-name:
          - "phpstan-phpunit"
          - "phpstan-strict-rules"
          - "phpstan-mockery"
          - "phpstan-doctrine"
          - "phpstan-symfony"
          - "phpstan-deprecation-rules"
          - "phpdoc-parser"
          - "phpstan-nette"
          - "phpstan-dibi"
          - "phpstan-webmozart-assert"
          - "phpstan-beberlei-assert"
        script:
          - "make tests"
          - "make phpstan"
        exclude:
          - extension-name: "phpstan-doctrine"
            php-version: "8.3"
          - extension-name: "phpstan-doctrine"
            php-version: "8.4"
          - extension-name: "phpstan-doctrine"
            php-version: "8.5"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: "phpstan/phpstan"
          ref: ${{ inputs.ref }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          ini-values: memory_limit=768M
          extensions: soap

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --ignore-platform-reqs"

      - name: "Download phpstan.phar"
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: actions/download-artifact@v4
          with: |
            name: phar-file
          attempt_limit: 5
          attempt_delay: 1000

      - name: "Checkout extension"
        uses: actions/checkout@v4
        with:
          repository: "phpstan/${{ matrix.extension-name }}"
          path: extension

      - uses: "ramsey/composer-install@v3"
        with:
          working-directory: "extension"

      - name: "Copy current PHAR"
        working-directory: extension
        run: |
          cp ../phpstan.phar vendor/phpstan/phpstan/phpstan.phar && \
          cp ../phpstan vendor/phpstan/phpstan/phpstan && \
          cp ../bootstrap.php vendor/phpstan/phpstan/bootstrap.php

      - name: "Script"
        working-directory: extension
        run: "${{ matrix.script }}"
